### ISSUE TITLE
하단 네비게이션 바 색상

### ISSUE THREAD

**Issue by gr2nsky** [gr2nsky/AndroidTeamProject#23]
// colors
<pre><code>
 name="menu_selected", #8F6614
 name="menu_nomal", #CAC673
</code></pre>
//selector
<pre><code>
android:color="@color/menu_selected"
android:color="@color/menu_nomal"
</code></pre>
----

![스크린샷 2021-06-18 오전 11 13 18](https://user-images.githubusercontent.com/44865986/122496258-66628780-d026-11eb-8906-10f0b5301641.png)

----

괜춘?

**Comment by jasper-oh** [comment]
굳 👍

**Comment by gr2nsky** [comment]
// colors
<pre><code>
 name="menu_selected", #CD5C5C
 name="menu_nomal", #565457


</code></pre>
//selector
<pre><code>
android:color="@color/menu_selected"
android:color="@color/menu_nomal"
</code></pre>
----

<img width="409" alt="스크린샷 2021-06-22 오후 4 51 14" src="https://user-images.githubusercontent.com/44865986/122885462-119e7400-d37a-11eb-8803-af8654f22092.png">

----

괜춘?
