### ISSUE TITLE
Splash Logo Exposure time 

### ISSUE THREAD

**Issue by jasper-oh** [gr2nsky/AndroidTeamProject#26]
5000 에서 2000 으로 줄였습니다. 

실행 해보시고 체감 적으로 얼마나 걸리게 하는게 좋을지 이야기 해주세요.

**Comment by gr2nsky** [comment]
2001은 어떤가요? 



는 농담이고 2초 딱 적당해 보입니다

**Comment by gr2nsky** [comment]
2초로 결정
